receivers:
    otlp:
        protocols:
            grpc:
                endpoint: '0.0.0.0:4317'
                include_metadata: true
            http:
                endpoint: '0.0.0.0:4318'
                max_request_body_size: 0
                include_metadata: true
                cors:
                    allowed_origins:
                        - 'https://*'
                        - 'http://*'
                    allowed_headers:
                        - 'X-Highlight-Request'
                        - 'Origin'
                        - 'Content-Type'
                        - 'Accept'
                        - 'Access-Control-Request-Headers'
                        - 'Access-Control-Request-Method'
                        - 'Access-Control-Allow-Origin'
                        - 'Access-Control-Allow-Methods'
                        - 'Access-Control-Max-Age'
                        - 'Referer'
                        - 'Traceparent'
                        - 'Tracestate'
                    max_age: 7200

exporters:
    logging:
        sampling_initial: 60
        sampling_thereafter: 1000
    otlphttp:
        # Using internal service URL pattern from Coolify
        endpoint: 'http://backend:8082/otel'
        timeout: 30s
        read_buffer_size: 32768
        write_buffer_size: 32768
        max_conns_per_host: 1000
        sending_queue:
            num_consumers: 100
            queue_size: 10000
        retry_on_failure:
            enabled: true
            initial_interval: 1s
            max_interval: 30s
            max_elapsed_time: 300s

processors:
    batch:
        metadata_keys:
            - x-highlight-project
        metadata_cardinality_limit: 1000
        timeout: 1s
        send_batch_size: 1000
        send_batch_max_size: 10000

service:
    telemetry:
        logs:
            level: 'info'
        metrics:
            address: '0.0.0.0:8888'
            level: detailed
    extensions: [headers_setter, health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp, logging]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp, logging]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp, logging]

extensions:
    headers_setter:
        headers:
            - action: upsert
              key: x-highlight-project
              from_context: x-highlight-project
    health_check:
        endpoint: '0.0.0.0:4319'
        path: '/health/status'